
import { SurveyData } from './types';

export const initialSurveyData: SurveyData = {
  section1: {
    q1_1_liderVarMi: '',
    q1_1_liderUnvan: '',
    q1_2_baglanti: '',
    q1_2_yatirimlar: '',
    q1_3_raporlama: '',
    q1_4_iso45001Gecis: '',
  },
  section2: {
    q2_1_dogalgaz: '',
    q2_1_elektrik: '',
    q2_1_fuelOil: '',
    q2_2_toplamPorsiyon: '',
    q2_2_porsiyonBasiEnerji: '',
    q2_3_suTuketimi: '',
    q2_4_porsiyonBasiSu: '',
    q2_5_atikSuYonetimi: '',
    q2_6_genelCop: '',
    q2_6_geriDonusum: '',
    q2_6_tehlikeliAtik: '',
    q2_7_geriKazanimOrani: '',
  },
  section3: {
    q3_1_aracSayisi: '',
    q3_1_aracDetaylari: '',
    q3_2_yakitTuketimi: '',
    q3_3_lojistikVerimlilik: '',
    q3_4_scope1Emisyon: '',
    q3_5_rotaOptimizasyonu: '',
    q3_6_satinAlmaPolitikasi: '',
  },
  section4: {
    q4_1_yesilKurulum: '',
    q4_1_kurulumOrani: '',
    q4_2_olcumYapiliyorMu: '',
    q4_2_pilotCalisma: '',
    q4_3_verimlilikEgitimleri: '',
  },
  section5: {
    q5_1_gidaAtigiOlcumu: '',
    q5_2_mutfakHazirlikFiresi: '',
    q5_2_fazlaUretimAtigi: '',
    q5_2_tabakArtigi: '',
    q5_3_tasimaModeliAtik: '',
    q5_4_yerindeUretimRaporlama: '',
    q5_5_degerlendirmeGidaBankasi: '',
    q5_5_degerlendirmeKompost: '',
    q5_5_degerlendirmeBertaraf: '',
  },
  section6: {
    q6_1_plastik: '',
    q6_1_kopuk: '',
    q6_1_bioCozunur: '',
    q6_1_yikanabilir: '',
    q6_2_yerindeYikanabilirOrani: '',
    q6_3_alternatifAmbalajAnalizi: '',
    q6_4_termoboxTemizlikOlcumu: '',
  },
  section7: {
    q7_1_yesilSatinAlma: '',
    q7_2_yerellikOrani: '',
    q7_3_tedarikciDenetimi: '',
  },
  section8: {
    q8_1_calisanSayisi: '',
    q8_1_toplamAdamSaat: '',
    q8_1_kazaSayisi: '',
    q8_1_kazaSiklikOrani: '',
    q8_1_egitimSaati: '',
    q8_2_psikolojikSaglikCalismasi: '',
    q8_3_memnuniyetKatilimOrani: '',
    q8_3_memnuniyetSkoru: '',
    q8_4_devirHizi: '',
    q8_5_farkindalikEgitimleri: '',
  },
  section9: {
    q9_1_gidaBankasiProtokolu: '',
    q9_1_bagislananGidaMiktari: '',
    q9_2_bitkiBazliMenuOrani: '',
    q9_2_besinDegeriSunumu: '',
    q9_3_surdurulebilirMenuSunumu: '',
  },
  section10: {
    q10_1_enerjiMaliyeti: '',
    q10_1_suMaliyeti: '',
    q10_1_atikBertarafMaliyeti: '',
    q10_1_lojistikYakitMaliyeti: '',
    q10_1_ambalajMaliyeti: '',
    q10_2_tasarrufMiktari: '',
    q10_3_gidaAtigiMaliyeti: '',
  },
};

export const SECTIONS = [
    { id: 1, title: "BÖLÜM 1: YÖNETİŞİM ('G') VE STRATEJİK UYUM", description: "Sürdürülebilirliğin firma stratejisi ve yönetimi ile ne kadar entegre olduğunu ölçer." },
    { id: 2, title: "BÖLÜM 2: ÇEVRESEL ('E') PERFORMANS: MERKEZİ TESİS (4.500 m²)", description: "4.500 m²'lik tesisinizin kaynak verimliliğini ölçer." },
    { id: 3, title: "BÖLÜM 3: ÇEVRESEL ('E') PERFORMANS: LOJİSTİK VE FİLO", description: "Modern sevkiyat filonuzun çevresel etkisini ölçer." },
    { id: 4, title: "BÖLÜM 4: ÇEVRESEL ('E') PERFORMANS: YERİNDE ÜRETİM MODELLERİ", description: "Müşteri tesislerindeki etkinizi ve 'sürdürülebilirlik ortağı' rolünüzü ölçer." },
    { id: 5, title: "BÖLÜM 5: TEMEL İSRAF ALANI: GIDA ATIĞI YÖNETİMİ", description: "En kritik israf alanınız olan gıda atığını (fire) ölçer." },
    { id: 6, title: "BÖLÜM 6: TEMEL İSRAF ALANI: AMBALAJ VE DÖNGÜSEL EKONOMİ", description: "Tek kullanımlık plastik ve diğer ambalajların kullanımını ölçer." },
    { id: 7, title: "BÖLÜM 7: SÜRDÜRÜLEBİLİR TEDARİK ZİNCİRİ", description: "'Tedarikçi iş birliği' politikanızı ve 'Türk mutfağı' misyonunuzu ölçer." },
    { id: 8, title: "BÖLÜM 8: SOSYAL ('S') PERFORMANS: ÇALIŞANLAR VE KÜLTÜR", description: "İSG politikanızı, eğitimleri ve kurumsal refahı ölçer." },
    { id: 9, title: "BÖLÜM 9: SOSYAL ('S') PERFORMANS: TOPLUM VE MÜŞTERİ", description: "'Dengeli beslenen toplum' hedefinizi ve toplumsal etkinizi ölçer." },
    { id: 10, title: "BÖLÜM 10: EKONOMİK ÖLÇÜMLER VE SENTEZ", description: "Sürdürülebilirlik çabalarının ekonomik boyutunu özetler." },
];
